### ISSUE TITLE
Could you let me know if there is anything else we need to do?

### ISSUE THREAD

**Issue by thurd92** [thurd92/Project#12]
- I am not sure what to do at this point.

**Comment by jak8oflegend** [comment]
have you done the dice roll code?

**Comment by jak8oflegend** [comment]
there are todo comments on each page
 as well you could alo write the background code for form 3 
should recieve the incomplete character and return the complete character 
add all the changes we made to  the db as well skills alignment race etc

**Comment by jak8oflegend** [comment]
you could also do some more documentation and check syntax im sure i missed some of my syntax errors ex variable names not being proper case

**Comment by jak8oflegend** [comment]
could also add cheat option that lets the user type values in for the rolls and all the error checking that goes with it or you could ad templates http://www.dandwiki.com/wiki/SRD:Templates
