### ISSUE TITLE
optional

### ISSUE THREAD

**Issue by jak8oflegend** [thurd92/Project#9]
add other roll options 
3d6
5d6 best 3
elite array 15 14 13 12 10 8
non elite array 13 12 11 10 9 8

**Comment by thurd92** [comment]
Could you be more specific on the details here?

**Comment by jak8oflegend** [comment]
add other roll options
3d6                                                      
rolls 3 6 sided die those are the values the text box will show 
5d6 best 3                                          
 rolls 5 6 sided die gets rid of lowest 2 those are the values the text box will show    
elite array 15 14 13 12 10 8
sets text box values to these
non elite array 13 12 11 10 9 8
sets text box values to these


baisically have a drop down menu that sets the dice roll and then re roll would check this and re roll based on this

**Comment by thurd92** [comment]
Thank you, will work on it.
